//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Title { get; set; }
        public string OrgName { get; set; }
        public string Password { get; set; }
        public string TimeZone { get; set; }
        public string PhotoLink { get; set; }
        public Nullable<short> DelFlag { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
